on:
  push:
    branches:
      - '**'
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  publish:
    uses: truemark/github-workflows/.github/workflows/javascript-library.yml@main
    if: github.actor != 'dependabot[bot]'
    with:
      node-versions: "[20,22,24]"
      publish-node-version: "24"
      develop-preid: "beta"
      branch-preid: "alpha"
    secrets:
      app-id: ${{ secrets.RELEASE_BOT_ID }}
      private-key: ${{ secrets.RELEASE_BOT_KEY }}
